### ISSUE TITLE
How to run the gzipper in production mode using angular 5

### ISSUE THREAD

**Issue by dineshguntha** [gios/gzipper#3] opened 2019-01-31 10:00 UTC
I am using to build this command
ng build && gzipper ./dist --prod 
But the production is not set. Can you please assist me in this issue?

**Comment by gios** [comment] 2019-01-31 16:12
You should set --prod args before gzipper command, like:
ng build --prod && gzipper ./dist

**Comment by dineshguntha** [comment] 2019-02-07 16:26
@gios  I am getting below this issue. Any assistance on it.

E:\Projects\Leading Indicators\code\UI\Leading Indicator_v2\LeadingIndicatorUI_v2>ng build --prod && gzipper ./dist
Your global Angular CLI version (1.7.3) is greater than your local
version (1.6.5). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
 10% building modules 3/4 modules 1 active ...\LeadingIndicatorUI_v2\src\styles.cssNode#moveTo was deprecated. Use Container#append.
 92% chunk asset optimization
<--- Last few GCs --->

[10576:00000000003A6CA0]   333335 ms: Mark-sweep 1337.1 (1467.5) -> 1337.0 (1468.5) MB, 1478.5 / 0.0 ms  allocation failure GC in
old space requested
[10576:00000000003A6CA0]   334857 ms: Mark-sweep 1337.0 (1468.5) -> 1337.0 (1428.5) MB, 1521.5 / 0.0 ms  last resort GC in old space requested
[10576:00000000003A6CA0]   336345 ms: Mark-sweep 1337.0 (1428.5) -> 1337.0 (1427.0) MB, 1487.6 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000007DFD625879 <JSObject>
    1: reduce_vars [00000263094822D1 <undefined>:~8136] [pc=00000246D60AA58B](this=0000011045B1FC59 <AST_VarDef map = 000002E77AA7E959>,tw=0000006014A416B9 <TreeWalker map = 000002A55FB945D9>,descend=0000021E43E8DAD9 <JSFunction (sfi = 000000D941246B19)>)
    2: arguments adaptor frame: 3->2
    3: visit [00000263094822D1 <undefined>:~8175] [pc=00000246D627D5C0](this=0000006014A416B9 <TreeWalk...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewFixedArray
 5: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::EnsureCapacity
 6: v8::internal::Dictionary<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::Add
 7: v8::internal::WasmDebugInfo::SetupForTesting
 8: v8::internal::WasmDebugInfo::SetupForTesting
 9: v8::internal::SharedFunctionInfo::SetScript
10: v8::internal::JSReceiver::class_name
11: v8::internal::SourcePositionTableIterator::Advance
12: v8::internal::SourcePositionTableIterator::Advance
13: 00000246D3B843C1

**Comment by gios** [comment] 2019-03-11 19:42
@dineshguntha is this issue still valid? You could have tried to update Angular and Angular CLI to version 6 if the issue is still reproduced.

**Comment by gios** [comment] 2019-03-15 19:33
@dineshguntha I closed this bug, if you still have a problem with the latest version of gzipper and Angular, please add additional details and I'll revise this problem again.

**Closed by gios** 2019-03-15 19:33 UTC
Labels: bug
